/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalho;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Statement;

/**
 *
 * @author Miguel e Luis
 */
public class Filme extends javax.swing.JFrame {
    
    public int idFilme;
    public String tituloFilme;
    public String classificacao;
    public String duracao;
    public String resumo;
    public Connection conexao;
    public String campoTitulo;
    public String campoClassificacao;
    public String campoDuracao;
    public String campoResumo;
    public int campoId;
    public static String valorCampo;


    public int getidFilme() {
        return idFilme;
    }

    public void setidFilme(int idFilme) {
        this.idFilme = idFilme;
    }

    public String gettituloFilme() {
        return tituloFilme;
    }

    public void settituloFilme(String tituloFilme) {
        this.tituloFilme = tituloFilme;
    }

    public String getclassificacao() {
        return classificacao;
    }

    public void setclassificacao(String classificacao){
        this.classificacao = classificacao;
    }

    public String getduracao() {
        return duracao;
    }

    public void setduracao (String duracao){
        this.duracao = duracao;
    }

    public String getResumo() {
        return resumo;
    }

    public void setResumo(String resumo) {
        this.resumo = resumo;
    }
    
    public Filme(Connection conexao){
        this.conexao = conexao;
    }
    
    public void setValorCampo(String valorCampo){
        Filme.valorCampo = valorCampo;
        
    }
    
    
    public ResultSet obterListaFilmes() throws SQLException{
        String sql = "select * from filme";
        
        PreparedStatement requisicao = this.conexao.prepareStatement(sql);
        return requisicao.executeQuery();
        }
    
    public boolean incluiFilme() throws SQLException{
    
    String sql = "insert into filme(titulo, "
            + "classificacao,"
            + "duracao,"
            + "resumo"
            + ") values (?, ?, ?, ?)";
    
    PreparedStatement requisicao = conexao.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
    
    requisicao.setString(1, tituloFilme);
    requisicao.setString(2, classificacao);
    requisicao.setString(3, duracao);
    requisicao.setString(4, resumo);
    requisicao.execute();
    ResultSet retorno = requisicao.getGeneratedKeys();
    if(retorno.next()){
        idFilme = retorno.getInt(1);
    }
    return true;
    }
    
    public void atualizaFilme() throws SQLException{
        String sql = "update filme set titulo=?,"
                + "classificacao=?,"
                + "duracao=?,"
                + "resumo=? where idFilme = ?";
        
        PreparedStatement requisicao = conexao.prepareStatement(sql);
        requisicao.setString(1, tituloFilme);
        requisicao.setString(2, classificacao);
        requisicao.setString(3, duracao);
        requisicao.setString(4, resumo);
        requisicao.setInt(5, idFilme);
        requisicao.execute();
    }
    
     public void deletaFilme() throws SQLException{
        String sql = "DELETE FROM filme WHERE idFilme = ?";
        
        PreparedStatement requisicao = this.conexao.prepareStatement(sql);
        requisicao.setInt(1, idFilme);
        requisicao.execute();
    }
    /**
     * Creates new form painel
     */
    public Filme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadastro = new javax.swing.JLabel();
        taTitulo = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        taClassificacao = new javax.swing.JTextField();
        lblClassificacao = new javax.swing.JLabel();
        taDuracao = new javax.swing.JTextField();
        lblDuracao = new javax.swing.JLabel();
        taResumo = new javax.swing.JTextField();
        lblResumo = new javax.swing.JLabel();
        AtualizarButton = new javax.swing.JButton();
        ExcluirButton = new javax.swing.JButton();
        listarButton = new javax.swing.JButton();
        incluirButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblCampo = new javax.swing.JTextArea();
        taId = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCadastro.setText("Cadastro de FIlmes");

        taTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taTituloActionPerformed(evt);
            }
        });

        lblTitulo.setText("Título");

        taClassificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taClassificacaoActionPerformed(evt);
            }
        });

        lblClassificacao.setText("Classificação");

        taDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taDuracaoActionPerformed(evt);
            }
        });

        lblDuracao.setText("Duração");

        taResumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taResumoActionPerformed(evt);
            }
        });

        lblResumo.setText("Resumo");

        AtualizarButton.setText("Atualizar");
        AtualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarButtonActionPerformed(evt);
            }
        });

        ExcluirButton.setText("Excluir");
        ExcluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirButtonActionPerformed(evt);
            }
        });

        listarButton.setText("Listar");
        listarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarButtonActionPerformed(evt);
            }
        });

        incluirButton1.setText("Incluir");
        incluirButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirButton1ActionPerformed(evt);
            }
        });

        lblCampo.setEditable(false);
        lblCampo.setColumns(20);
        lblCampo.setRows(5);
        jScrollPane1.setViewportView(lblCampo);

        taId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taIdActionPerformed(evt);
            }
        });

        lblId.setText("id (caso queira excluir ou atualizar)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(incluirButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(ExcluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(AtualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblId)
                                .addGap(18, 18, 18)
                                .addComponent(taId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(listarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblResumo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(taResumo, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(37, 37, 37)
                                    .addComponent(taTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(37, 37, 37)
                                            .addComponent(taDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(taClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(120, 120, 120))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCadastro)
                .addGap(198, 198, 198))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblResumo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taResumo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AtualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(incluirButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExcluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112)
                        .addComponent(listarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taTituloActionPerformed

    private void taClassificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taClassificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taClassificacaoActionPerformed

    private void taDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taDuracaoActionPerformed

    private void taResumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taResumoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taResumoActionPerformed

    private void AtualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarButtonActionPerformed
        // TODO add your handling code here:
        
        
        campoId = Integer.parseInt(taId.getText());
        campoTitulo = taTitulo.getText();
        campoClassificacao = taClassificacao.getText();
        campoDuracao = taDuracao.getText();
        campoResumo = taResumo.getText();
              
        Atualizar atualizar = new Atualizar(campoId, campoTitulo, campoClassificacao, campoDuracao, campoResumo);
        
        atualizar.atualizarFilme();
    }//GEN-LAST:event_AtualizarButtonActionPerformed
        
    
    private void ExcluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirButtonActionPerformed
        // TODO add your handling code here:
        
        campoId = Integer.parseInt(taId.getText());
              
        Excluir excluir = new Excluir(campoId);
        
        excluir.excluirFilme();   
    }//GEN-LAST:event_ExcluirButtonActionPerformed
        
    private void listarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarButtonActionPerformed
        // TODO add your handling code here:
        
        Listar listar = new Listar();
        listar.listarFilme();
        
        lblCampo.setText(valorCampo);
        
    }//GEN-LAST:event_listarButtonActionPerformed

    private void incluirButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirButton1ActionPerformed
        // TODO add your handling code here:
        
        campoTitulo = taTitulo.getText();
        campoClassificacao = taClassificacao.getText();
        campoDuracao = taDuracao.getText();
        campoResumo = taResumo.getText();
        
        Incluir inclui = new Incluir (campoTitulo, campoClassificacao, campoDuracao, campoResumo);
        
        inclui.incluirFilme();
    }//GEN-LAST:event_incluirButton1ActionPerformed

    private void taIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Filme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Filme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Filme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Filme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Filme().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtualizarButton;
    private javax.swing.JButton ExcluirButton;
    private javax.swing.JButton incluirButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCadastro;
    javax.swing.JTextArea lblCampo;
    private javax.swing.JLabel lblClassificacao;
    private javax.swing.JLabel lblDuracao;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblResumo;
    private javax.swing.JLabel lblTitulo;
    javax.swing.JButton listarButton;
    javax.swing.JTextField taClassificacao;
    javax.swing.JTextField taDuracao;
    javax.swing.JTextField taId;
    javax.swing.JTextField taResumo;
    javax.swing.JTextField taTitulo;
    // End of variables declaration//GEN-END:variables

}
